### ISSUE TITLE
Add readme 

### ISSUE THREAD

**Issue by bossbossk20** [bossbossk20/IoT#2]
this repo still don't have a readme file yet

just simple PR

**Comment by felipesousa** [comment]
hello @bossbossk20, could you leave a little more specific about what is this project? could you categorize it as a set of IOT-based experiments with NodeJS? :octocat: 🐙

**Comment by bossbossk20** [comment]
it's my learning space for IoT, dont worry just creates a readme.md  and write it @felipesousa  :joy:

**Comment by felipesousa** [comment]
@bossbossk20 nice! #3  :) :octocat:
